# Generated by Django 5.2.7 on 2025-10-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_categories_alter_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='categories',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.category'),
        ),
    ]
